fs.makeDir("/gay")
local back = http.get("https://www.dropbox.com/s/p2kpl3nkx54qai9/termutils.lua?dl=1")
local file = fs.open("/gay/termutils.lua", "w")
file.write(back.readAll())
file.close()
back.close()